AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Auto Scaling Group

Parameters:
  MinSize:
    Type: Number
    Description: Minimum number of instances in the Auto Scaling Group
    Default: 2
  MaxSize:
    Type: Number
    Description: Maximum number of instances in the Auto Scaling Group
    Default: 3
  DesiredCapacity:
    Type: Number
    Description: Desired number of instances in the Auto Scaling Group
    Default: 2
  VpcId:
    Type: String
    Description: VPC ID where the Auto Scaling Group will be launched
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs for the Auto Scaling Group

Resources:
  CrudAutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      LaunchTemplate:
        LaunchTemplateId: 'lt-0b95d7d47bb63afc7'  # Replace with your Launch Template ID
        Version: '$Default'
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      DesiredCapacity: !Ref DesiredCapacity
      VPCZoneIdentifier: !Ref SubnetIds
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      TargetGroupARNs:
        - 'arn:aws:elasticloadbalancing:us-east-1:361478966802:targetgroup/crudtargetgroup/fc5231d975974549'  # Replace with your Target Group ARN
      Tags:
        - Key: Name
          Value: crudASGinstance
          PropagateAtLaunch: true

Outputs:
  AutoScalingGroupName:
    Description: "Auto Scaling Group Name"
    Value: !Ref CrudAutoScalingGroup
