AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for ALB, Target Group, and Listener

Parameters:
  VpcId:
    Type: String
    Description: VPC ID
  SecurityGroupId:
    Type: String
    Description: Security Group ID for ALB

Resources:
  CrudALB:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Subnets:
        - subnet-0157b489891a646b9  # Replace with your subnet IDs
        - subnet-0310cca42357a59fd  # Replace with your subnet IDs
      SecurityGroups:
        - !Ref SecurityGroupId
      Scheme: internet-facing
      IpAddressType: ipv4
      Name: crudALB

  CrudTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: 80
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 60
      HealthCheckTimeoutSeconds: 50
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 10
      HealthCheckPath: /
      Matcher:
        HttpCode: '200'
      TargetType: instance

  CrudListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref CrudTargetGroup
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref CrudTargetGroup
                Weight: 1
            TargetGroupStickinessConfig:
              Enabled: false
      LoadBalancerArn: !Ref CrudALB
      Port: 80
      Protocol: HTTP

Outputs:
  LoadBalancerDNS:
    Description: DNS name of the created ALB
    Value: !GetAtt CrudALB.DNSName
