AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template for Amazon Aurora RDS Cluster

Parameters:
  DBName:
    Type: String
    Default: phpcrud
    Description: The name of the initial database.

  MasterUsername:
    Type: String
    Default: admin
    Description: The master username for the RDS instance.

  MasterUserPassword:
    Type: String
    NoEcho: true
    Description: The master password for the RDS instance.

  DBClusterName:
    Type: String
    Default: cruddbcluster
    Description: The name of the Aurora RDS cluster.

Resources:
  RDSDBCluster:
    Type: "AWS::RDS::DBCluster"
    Properties:
      Engine: aurora-mysql
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DatabaseName: !Ref DBName
      BackupRetentionPeriod: 1
      PreferredBackupWindow: "03:47-04:17"
      Port: 3306
      EngineVersion: "8.0.mysql_aurora.3.04.0"
      DBClusterIdentifier: !Ref DBClusterName
      StorageEncrypted: false
      AvailabilityZones:
        - us-east-1a
        - us-east-1b
      DBSubnetGroupName: cruddbsubnetgroup
      VpcSecurityGroupIds:
        - sg-0f4961c511b173019
      Tags:
        - Key: Name
          Value: "AuroraDBCluster"
  RDSDBInstance1:
    Type: "AWS::RDS::DBInstance"
    Properties:
      Engine: aurora-mysql
      DBInstanceIdentifier: !Sub "${DBClusterName}-instance-1"
      DBClusterIdentifier: !Ref DBClusterName
      DBInstanceClass: db.t3.medium
  RDSDBInstance2:
    Type: "AWS::RDS::DBInstance"
    Properties:
      Engine: aurora-mysql
      DBInstanceIdentifier: !Sub "${DBClusterName}-instance-2"
      DBClusterIdentifier: !Ref DBClusterName
      DBInstanceClass: db.t3.medium
