AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for Amazon EFS

Parameters:
  EFSName:
    Description: Name of the EFS file system
    Type: String
    Default: crudEFS

Resources:
  EFSFileSystem:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      FileSystemTags:
        - Key: Name
          Value: !Ref EFSName

  MountTargetSubnet1:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: subnet-06809f1194e68840c  # Use the appropriate SubnetId from the describe-mount-targets output
      SecurityGroups:   # Add appropriate security groups
        - sg-0123456789abcdef0  # Specify the security group ID
      IpAddress: 10.0.3.42

  MountTargetSubnet2:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: subnet-04eb20b7d7ed0944d  # Use the appropriate SubnetId from the describe-mount-targets output
      SecurityGroups:   # Add appropriate security groups
        - sg-0123456789abcdef0  # Specify the security group ID
      IpAddress: 10.0.2.175

Outputs:
  EFSFileSystemID:
    Description: "The ID of the created EFS file system"
    Value: !Ref EFSFileSystem
